git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side
    - colorArg: always
      pager: delta --dark --paging=never
    - {}   # cycle to this with | for the plain unstyled diff
