git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side
    - colorArg: always
      pager: delta --dark --paging=never
    - type: rawGit

os:
  editPreset: 'nvim-remote'

gui:
  theme:
    activeBorderColor:
      - "#a2b08d"
      - bold
    inactiveBorderColor:
      - "#948e74"
    searchingActiveBorderColor:
      - "#6e857b"
      - bold
    optionsTextColor:
      - "#a2b08d"
    selectedLineBgColor:
      - "#2f322c"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#a2b08d"
    cherryPickedCommitBgColor:
      - "#6e857b"
    markedBaseCommitFgColor:
      - "#6e857b"
    markedBaseCommitBgColor:
      - "#ce7a71"
    unstagedChangesColor:
      - "#ce7a71"
    defaultFgColor:
      - "#f4f6eb"
